# Project Metadata
sonar.projectKey=thedevmystic_mge
sonar.organization=thedevmystic
sonar.projectName=mge
sonar.projectVersion=0.1
sonar.sourceEncoding=UTF-8

# Source Structure
sonar.sources=apps,engine
sonar.tests=engine
sonar.exclusions=**/test/**/*

# Add Tests Back
sonar.test.inclusions=**/test/**/*

# Language Files
sonar.c.file.suffixes=.c,.h
sonar.cpp.file.suffixes=.cpp,.hpp
sonar.python.file.suffixes=.py

# Coverage Report
sonar.coverageReportPaths=coverage.xml
