# CI/CD Workflow
name: "CI/CD"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6

      - name: CI/CD
        uses: thedevmystic/github-actions/cpp-compatibility-check@main
