# Pre Commit Workflow
name: "Pre Commit"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6

      - name: Test Pre Commit Action
        uses: thedevmystic/github-actions/pre-commit@main
