# Workflow for SonarQube Cloud
name: "SonarQube Cloud"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  sonarqube-cloud:
    runs-on: ubuntu-latest
    env:
      BUILD_WRAPPER_OUT_DIR: build_wrapper_output_directory
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Install Build Wrapper
        uses: SonarSource/sonarqube-scan-action/install-build-wrapper@v8

      - name: Install Coverage Tools
        run: sudo apt-get update && sudo apt-get install -y gcovr

      - name: Run Build Wrapper
        run: |
          mkdir build
          cmake -S . -B build -DCMAKE_CXX_FLAGS="--coverage" -DCMAKE_C_FLAGS="--coverage"
          build-wrapper-linux-x86-64 --out-dir ${{ env.BUILD_WRAPPER_OUT_DIR }} cmake --build build/ --config Release

      - name: Run Tests
        run: |
          cd build
          ctest --output-on-failure

      - name: Generate Coverage Report
        run: |
          gcovr --sonarqube coverage.xml -r . --filter engine/ --exclude build/

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v8
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            --define sonar.cfamily.compile-commands=${{ env.BUILD_WRAPPER_OUT_DIR }}/compile_commands.json
            --define sonar.gcov.reportsPath=coverage.xml
